variables:
  REGISTRY_IP: "10.71.103.108"
  REGISTRY_HOSTNAME: "docker-build-proxy.novalocal"
  REGISTRY_PORT: "5000"
  DOCKER_HOST: "tcp://unlhcc__docker:2375"
  SINGULARITY_TAG: 2.3.1

services:
  - unlhcc/docker:hccdind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  except:
    - master
  image: docker:latest
  tags:
    - docker
  variables:
    SW_NAMESPACE: "$REGISTRY_HOSTNAME:$REGISTRY_PORT/$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python py-pip git
    - pip install git+https://github.com/acaprez/docker-registry-client.git@hcc git+https://github.com/unlhcc/shipwright.git@hcc
    - echo "$REGISTRY_IP $REGISTRY_HOSTNAME" >> /etc/hosts
    - export REQUESTS_CA_BUNDLE=${CI_PROJECT_DIR}/ca.crt
  script:
    - shipwright build --registry-login https://${REGISTRY_HOSTNAME}:${REGISTRY_PORT}
    - shipwright push --registry-login https://${REGISTRY_HOSTNAME}:${REGISTRY_PORT}

test:
  stage: test
  except:
    - master
  image: $HCC_REPO_NAMESPACE/singularity:$SINGULARITY_TAG
  tags:
    - docker
  script:
    - echo "$REGISTRY_IP $REGISTRY_HOSTNAME" >> /etc/hosts
    - su - singularity
    - ./testall.sh

deploy:
  stage: deploy
  image: docker:latest
  only:
    - master
  tags:
    - docker
  variables:
    SW_NAMESPACE: "docker.io/$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python py-pip git
    - pip install git+https://github.com/acaprez/docker-registry-client.git@hcc git+https://github.com/unlhcc/shipwright.git@hcc
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - shipwright build --registry-login "https://docker.io --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD"
    - shipwright push --registry-login "https://docker.io --username=$DOCKERHUB_USER --password=$DOCKERHUB_PASSWORD"

