variables:
  REGISTRY_IP: "10.71.103.108"
  REGISTRY_HOSTNAME: "docker-build-proxy.novalocal"
  REGISTRY_PORT: "5000"
  DOCKER_HOST: "tcp://unlhcc__docker:2375"

services:
  - unlhcc/docker:hccdind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  except:
    - master
  image: docker:latest
  tags:
    - docker
  variables:
    SW_NAMESPACE: "$REGISTRY_HOSTNAME:$REGISTRY_PORT/$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python py-pip git
    - pip install shipwright==0.9.0a
  script:
    - shipwright build --pull-cache
    - shipwright push --pull-cache

test:
  stage: test
  except:
    - master
  image: $HCC_REPO_NAMESPACE/singularity
  tags:
    - docker
  script:
    - echo "$REGISTRY_IP $REGISTRY_HOSTNAME" >> /etc/hosts
    - su - singularity
    - ./testall.sh

deploy:
  stage: deploy
  image: docker:latest
  only:
    - master
  tags:
    - docker
  variables:
    SW_NAMESPACE: "$HCC_REPO_NAMESPACE"
  before_script:
    - apk add --no-cache python py-pip git
    - pip install shipwright==0.9.0a
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - shipwright build --pull-cache
    - shipwright push --pull-cache

